language: rust

before_install:
  - git submodule update --remote

install:
  - cd codegen
  - cargo run

script:
  - cd ..
  - cargo build

after_success:
  - pwd
  - cd
  - pwd
  - .travis/push.sh

#deploy:
  #provider: pages
  #skip-cleanup: true
  #github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  #keep-history: true
  #target-branch: CI
  #local-dir: "src/"
  #on:
    #branch: CI

