language: rust

install:
  - cd codegen
  - cargo run

before_script:
  - git submodule update --remote

script: cargo build

after_success:
  - push.sh

#deploy:
  #provider: pages
  #skip-cleanup: true
  #github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  #keep-history: true
  #target-branch: CI
  #local-dir: "src/"
  #on:
    #branch: CI
